### PR TITLE
Fixes #3 - Support GridLayoutManager

### LINKED ISSUE #3: Add support for GridLayoutManager
The API looks great, though I would like to use it with `GridLayoutManager` as well.

### PR DESCRIPTION
**Pull request by KevinTCoughlin**
This fixes #3 - Support GridLayoutManager.

It's an extension of the base Bookends class that performs a span size lookup to determine the number of spans a view should take up. By default headers and footers take up the number of spans in the grid layout. There's also a constructor that allows for a custom span size lookup definition.

There's an unchecked assignment I could use your help w/ @mlapadula

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
Hmm brought in some extras, closing while I fix.

**Comment by KevinTCoughlin** [comment]
Unsure of how navigation in the sample app to show an example with this class should be. Will add once that's figured out.

**Comment by mlapadula** [comment]
You can fix the unchecked cast warning by applying this diff. Essentially since Bookends requires a `<T extends RecyclerView.Adapter>` you need to ensure that the subclass also has the same constraint. 

``` diff
diff --git a/bookends/src/main/java/com/tumblr/bookends/GridBookends.java b/bookends/src/main/java/com/tumblr/bookends/GridBookends.java
index 78aa439..3c4d2a5 100644
--- a/bookends/src/main/java/com/tumblr/bookends/GridBookends.java
+++ b/bookends/src/main/java/com/tumblr/bookends/GridBookends.java
@@ -14,14 +14,14 @@ import android.support.v7.widget.RecyclerView;
  *
  * Created by kevincoughlin on 5/21/15.
  */
-public class GridBookends extends Bookends {
+public class GridBookends<T extends RecyclerView.Adapter> extends Bookends<T> {
        /**
         * Constructor.
         *
         * @param base
         *              the adapter to wrap
         */
-   public GridBookends(RecyclerView.Adapter base) {
+ public GridBookends(T base) {
                super(base);
        }

@@ -33,7 +33,7 @@ public class GridBookends extends Bookends {
         * @param gridLayoutManager
         *              the grid layout manager to perform a span size lookup on
         */
-   public GridBookends(final RecyclerView.Adapter base, @NonNull final GridLayoutManager gridLayoutManager) {
+ public GridBookends(final T base, @NonNull final GridLayoutManager gridLayoutManager) {
                this(base);
                gridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
                        @Override
@@ -55,7 +55,7 @@ public class GridBookends extends Bookends {
         * @param spanSizeLookup
         *              the span size lookup to perform
         */
-   public GridBookends(final RecyclerView.Adapter base, @NonNull final GridLayoutManager gridLayoutManager,
+ public GridBookends(final T base, @NonNull final GridLayoutManager gridLayoutManager,
                            @NonNull GridLayoutManager.SpanSizeLookup spanSizeLookup) {
                this(base);
                gridLayoutManager.setSpanSizeLookup(spanSizeLookup);
```

**Comment by mlapadula** [comment]
Other than that the code LGTM. 

For the sample app: how about adding a little drawer to the left-hand side, where the user can toggle between the regular Bookends example and a GridBookends example?

**Comment by mlapadula** [comment]
Also:
- It'd be cool to update the README and mention that GridLayoutManager is now supported.
- Do you have the github permissions to merge this? If not, lemme make you an admin of the repo (if I can).

**Comment by KevinTCoughlin** [comment]
@mlapadula I don't currently have write access :/

I'll update the type, README, and add an example asap.

**Comment by mlapadula** [comment]
Hmm, after looking at it a bit I don't think I can add you either -- you need one of these guys to do it: https://github.com/orgs/tumblr/teams/owners

(@dangermike made these repos in the first place so he's probably the guy to ping)

**Pull request closed without merging**
